name: First Workflow

on:
    push:
        branches:
            - main

jobs:
    example-job:
        runs-on: ubuntu-latest

        steps:
            - name: Print a welcome message
              run: echo "Hello, world!"

            - name: Checkout code
              uses: actions/checkout@v7
              
            - name: List files in the repository
              run: ls -la
